version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      #  # Mount your local codebase to the container.
      # - "${PWD}:/${MAGE_CODE_PATH}"
      # # Store the data output on local machine to easily debug (optional).
      # - "~/.mage_data:/$MAGE_CODE_PATH/mage_data"
      - .:/home/src/
    restart: on-failure:5
    networks:
      - my-network
    depends_on:
      - magic-database-2
    stdin_open: true # used for interactive debugging
    tty: true # used for interactive debugging

  magic-database-2:
    image: pgvector/pgvector:0.6.0-pg16
    env_file:
      - .env
    ports:
      - "5443:5432"
    volumes:
      - ~/.postgres/data:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge